export SKIP_TLS="true" #if TLS to be enabled comment the whole line
#export SKIP_FETCHJAR="true" #Use only for testing. In Prod setup, comment this line
#export JAR_FILE="CONFIG_rel-v1.13.1-main.jar"
#export GIT_URL="https://github.com/Francy93/CPP-Projects.git"
#export GIT_BRANCH="master"
export JAR_URL="https://trialxvw53e.jfrog.io/artifactory/testrepo-generic-local/spring-petclinic-3.5.4-SNAPSHOT.jar"
export ARTIFACTORY_USER="USER"
export ARTIFACTORY_PASS="PASSWORD"
export SSD_URL="https://ssd-host"
export SSD_TEAMTOKEN="TOKEN"
